### ISSUE TITLE
How to create port in docker-compose.yml

### ISSUE THREAD

**Issue by hugo-leij** [chrisns/docker-node-sonos-http-api#49]
Dear,

Nice to see that someone has turned this into a docker container, works great.
On my raspberry it runs as it should. For the people who also like to work with a yml file with this one:

Create a folder in /home/pi/, i called it sonos-api en place the docker-compose.yml  as following
```
version: '3.3'
services:
    docker-node-sonos-http-api:
        network_mode: host
        container_name: sonos-api
        restart: always
        volumes:
            - '/home/pi/sonos-api/settings:/app/settings'
            - '/home/pi/sonos-api/clips:/app/static/clips'
            - '/home/pi/sonos-api/cache:/app/cache'
            - '/home/pi/sonos-api/presets:/app/presets'
        image: chrisns/docker-node-sonos-http-api
```

* I didn't first create the folders on my PI

**Question:**
Is it possible to create a variable for the port, something like
```
   ports:
      - 8181:5005
```
